//! Page-level domain types.
//!
//! A *page* is the unit of long-term memory — one markdown file under
//! `<data_dir>/wiki/`. Pages live in tiers (working/episodic/semantic/
//! procedural) and are versioned in place via supersession (an old
//! `is_latest=false` row links to the new `is_latest=true` row through
//! [`Page::supersedes`]).

use std::str::FromStr;

use jiff::Timestamp;
use serde::{Deserialize, Serialize};

use crate::ids::{PageId, PagePath, ProjectId, WorkspaceId};

/// Lifetime classification for a page.
///
/// Adopted from agentmemory's four-tier model, simplified. See
/// [`docs/design-decisions.md`](../../docs/design-decisions.md) §7.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Tier {
    /// Current session: last N observations, current files.
    Working,
    /// Per-session summaries with concept tags and files touched.
    Episodic,
    /// Distilled facts/preferences/architecture notes — wiki pages proper.
    Semantic,
    /// Repeated patterns extracted from episodic clusters.
    Procedural,
}

/// Input for upserting a page. Generated by the wiki layer, consumed by
/// the store's writer actor.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NewPage {
    /// Owning workspace.
    pub workspace_id: WorkspaceId,
    /// Owning project.
    pub project_id: ProjectId,
    /// Relative path within the wiki tree.
    pub path: PagePath,
    /// Page title (rendered from frontmatter or the first H1).
    pub title: String,
    /// Markdown body excluding the YAML frontmatter.
    pub body: String,
    /// Tier classification.
    pub tier: Tier,
    /// Frontmatter, stored as JSON for cheap querying.
    pub frontmatter_json: serde_json::Value,
    /// `true` to mark the page as user-pinned (never decay).
    pub pinned: bool,
    /// Outgoing links discovered in the page body.
    ///
    /// The store resolves these against the latest page rows in the target
    /// project (the source's own project for bare links, or the named
    /// project for a cross-project `[[project:path]]` link) and keeps
    /// unresolved forward links as `to_page_id = NULL`.
    pub links: Vec<LinkTarget>,
    /// Multi-user attribution: the registered user (v0.8 `users` table)
    /// that made this write, when resolved by the auth middleware.
    /// `None` for rung-0 (anonymous) and rung-1 (root token — root
    /// isn't a `users` row; the human-readable identity goes into the
    /// frontmatter `last_modified_by` block instead). `Some` for
    /// rung-2 (DB user) writes; persists to `pages.author_id`
    /// via V15. Defaults to `None` for backward compat — every existing
    /// call site that constructs `NewPage` without filling this field
    /// gets the pre-multi-user behaviour.
    #[serde(default)]
    pub author_id: Option<crate::UserId>,
}

/// A link target discovered in a page body.
///
/// A bare `[[path]]` / `[label](path)` resolves within the source page's
/// own project (`workspace`/`project` both `None`). A `[[project:path]]`
/// link names a sibling project in the same workspace; a
/// `[[workspace/project:path]]` link crosses workspaces. Making
/// cross-project dependencies explicit edges is what turns the per-project
/// wikis into one graph.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct LinkTarget {
    /// Cross-workspace qualifier. `None` = same workspace as the source.
    pub workspace: Option<String>,
    /// Cross-project qualifier. `None` = same project as the source.
    pub project: Option<String>,
    /// Wiki path within the target project (root-relative).
    pub path: PagePath,
}

impl LinkTarget {
    /// A link resolving within the source page's own project.
    #[must_use]
    pub fn local(path: PagePath) -> Self {
        Self {
            workspace: None,
            project: None,
            path,
        }
    }

    /// Whether this link names a different project than its source.
    #[must_use]
    pub fn is_cross_project(&self) -> bool {
        self.project.is_some()
    }
}

impl From<PagePath> for LinkTarget {
    fn from(path: PagePath) -> Self {
        Self::local(path)
    }
}

/// Materialised view of a page row.
#[derive(Clone, Debug)]
pub struct Page {
    /// Stable identifier for this page *version*.
    pub id: PageId,
    /// Owning workspace.
    pub workspace_id: WorkspaceId,
    /// Owning project.
    pub project_id: ProjectId,
    /// Relative path within the wiki tree.
    pub path: PagePath,
    /// Page title.
    pub title: String,
    /// Markdown body.
    pub body: String,
    /// SHA-256 of [`Self::body`].
    pub body_sha256: [u8; 32],
    /// Tier classification.
    pub tier: Tier,
    /// Frontmatter as JSON.
    pub frontmatter: serde_json::Value,
    /// `true` if this row is the current visible version.
    pub is_latest: bool,
    /// Previous version of this page, if any.
    pub supersedes: Option<PageId>,
    /// `true` if the user has pinned this page (decay sweep skips it).
    pub pinned: bool,
    /// Wall-clock creation time of *this version*.
    pub created_at: Timestamp,
    /// Wall-clock last-update time of *this version*.
    pub updated_at: Timestamp,
}

impl Tier {
    /// Canonical short string for storage and serialisation.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Working => "working",
            Self::Episodic => "episodic",
            Self::Semantic => "semantic",
            Self::Procedural => "procedural",
        }
    }
}

impl FromStr for Tier {
    type Err = crate::MemoryError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "working" => Ok(Self::Working),
            "episodic" => Ok(Self::Episodic),
            "semantic" => Ok(Self::Semantic),
            "procedural" => Ok(Self::Procedural),
            other => Err(crate::MemoryError::MalformedRecord(format!(
                "unknown tier: {other}"
            ))),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tier_round_trips() {
        for t in [
            Tier::Working,
            Tier::Episodic,
            Tier::Semantic,
            Tier::Procedural,
        ] {
            assert_eq!(t.as_str().parse::<Tier>().unwrap(), t);
        }
    }

    #[test]
    fn tier_rejects_unknown() {
        assert!("nope".parse::<Tier>().is_err());
    }

    #[test]
    fn tier_serde() {
        assert_eq!(
            serde_json::to_string(&Tier::Procedural).unwrap(),
            "\"procedural\""
        );
    }
}
